# Directories and file names
DIR_DATA = '../data/'
FILE_CSV_TRACKER = 'tracker.csv'
FILE_JSON_USER = 'user_data.json'

# Settings
CONFIG_PAD_CHAR = ' '
CONFIG_MAX_LENGTH = 12

# Values
INCOME_KEYWORDS = ('ADJUST', 'ADJUSTMENT', 'INCOME', 'PAYCHECK')
WINDOW_TITLE = 'Budget Tracker'
COLOR_BG = '#142025'
COLOR_BG_SEC = '#223239'
COLOR_SEC = '#142C60'
COLOR_BTN = '#0FC2C8'
COLOR_TXT = '#BDD4EB'
COLOR_TXT_IN = '#142B42'
COLOR_GOOD = '#5ACA67'
COLOR_DANGER = '#CA5A5A'

# User defaults
USER_SAVE_GOAL = 5600
USER_AIM_BUDGET = 550
USER_SAVE_PERCENTAGE = 0.65
